# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Kodi systemd daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

